### ISSUE TITLE
version 0.8.0 conflict with clojure 1.9

### ISSUE THREAD

**Issue by jiacai2050** [sunng87/papaline#3]
Exception
```
   Call to clojure.core/refer-clojure did not conform to spec: In: [2
   1] val: :as fails at: [:args :exclude :op :quoted-spec :spec]
   predicate: #{:exclude} In: [2 1] val: :as fails at: [:args :only
   :op :quoted-spec :spec] predicate: #{:only} In: [2 1] val: :as
   fails at: [:args :rename :op :quoted-spec :spec] predicate:
   #{:rename} In: [2] val: (quote :as) fails at: [:args :exclude :op
   :spec] predicate: #{:exclude} In: [2] val: (quote :as) fails at:
   [:args :only :op :spec] predicate: #{:only} In: [2] val: (quote
   :as) fails at: [:args :rename :op :spec] predicate: #{:rename}
```
bump core.async to 0.3.465 will solve this.

**Comment by sunng87** [comment]
Thank you! Let me bump it.

**Comment by sunng87** [comment]
Released in 0.9.0. 

Let me know with anything I could help about this lib.

**Comment by ylgrgyq** [comment]
Cloud you tell me why delete "javac-options" configuration in 0.9.0? Currently, "papaline 0.9.0" will force client upgrade to JDK9 because it's jar file downloaded from clojar is compiled under JDK9. But I found that it seems compatible with JDK8 based on several basic tests.

**Comment by sunng87** [comment]
My bad… I will fix it tonight

**Comment by sunng87** [comment]
0.9.1 is uploaded, compiled to 1.8 source/target level

**Comment by ylgrgyq** [comment]
Thanks a lot.  :satisfied:
